name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: idlemmo-conquest
  DEPLOY_PATH: /home/${{ secrets.VPS_USER }}/idlemmo-conquest

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build
        env:
          DB_FILE_NAME: ${{ secrets.DB_FILE_NAME }}
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}

  deploy:
    needs: build
    environment: production
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          timeout: 600s
          script: |
            set -e

            # Update package list
            sudo apt update

            # Install Node.js 22 if not present
            if ! command -v node &> /dev/null || [[ $(node -v | cut -d'.' -f1 | cut -d'v' -f2) -lt 22 ]]; then
              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Install pnpm if not present
            if ! command -v pnpm &> /dev/null; then
              sudo npm install -g pnpm
            fi

            # Install PM2 if not present
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Create deployment directory
            mkdir -p ${{ env.DEPLOY_PATH }}
            cd ${{ env.DEPLOY_PATH }}

            # Stop existing PM2 process before deployment
            pm2 delete ${{ env.APP_NAME }} 2>/dev/null || true

            # Clone/pull latest code
            if [ ! -d ".git" ]; then
              git clone ${{ github.server_url }}/${{ github.repository }}.git .
            else
              git fetch origin
              git reset --hard origin/main
            fi

            # Create .env file
            echo '${{ secrets.ENV_FILE }}' > .env
            chmod 600 .env

            # Install dependencies and build
            export NODE_OPTIONS="--max-old-space-size=1024"
            pnpm install --frozen-lockfile
            pnpm build

            # Run database migrations
            pnpm run drizzle:migrate

            # Start new PM2 process
            pm2 start "pnpm start" \
              --name "${{ env.APP_NAME }}" \
              --cwd "${{ env.DEPLOY_PATH }}" \
              --env NODE_ENV=production \
              --env PORT=3000 \
              --max-memory-restart 512M

            # Save PM2 configuration
            pm2 save

            # Setup PM2 startup script (run once)
            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ${{ secrets.VPS_USER }} --hp /home/${{ secrets.VPS_USER }} || true

            # Clean up
            pnpm store prune
