name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: idlemmo-conquest
  DEPLOY_PATH: /home/${{ secrets.VPS_USER }}/idlemmo-conquest

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build
        env:
          DB_FILE_NAME: ${{ secrets.DB_FILE_NAME }}
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}

      - name: Create deployment package
        run: |
          # Create a deployment archive with only necessary files
          tar -czf deploy.tar.gz \
            .next \
            public \
            package.json \
            pnpm-lock.yaml \
            next.config.* \
            drizzle \
            src/lib/db \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=.next/cache

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deploy.tar.gz
          retention-days: 1

  deploy:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - name: Copy deployment package to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: 'deploy.tar.gz'
          target: '/tmp/'

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          timeout: 600s
          script: |
            set -e

            # Install dependencies if needed
            if ! command -v node &> /dev/null; then
              sudo apk add --no-cache nodejs npm
            fi

            if ! command -v pnpm &> /dev/null; then
              sudo npm install -g pnpm
            fi

            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Create deployment directory
            mkdir -p ${{ env.DEPLOY_PATH }}
            cd ${{ env.DEPLOY_PATH }}

            # Stop existing PM2 process before deployment
            pm2 delete ${{ env.APP_NAME }} 2>/dev/null || true

            # Extract deployment package
            tar -xzf /tmp/deploy.tar.gz
            rm /tmp/deploy.tar.gz

            # Create .env file
            echo '${{ secrets.ENV_FILE }}' > .env
            chmod 600 .env

            # Install only production dependencies (much faster and less memory)
            export NODE_OPTIONS="--max-old-space-size=1024"
            pnpm install --prod --frozen-lockfile

            # Run database migrations
            pnpm run drizzle:migrate

            # Start new PM2 process
            pm2 start "pnpm start" \
              --name "${{ env.APP_NAME }}" \
              --cwd "${{ env.DEPLOY_PATH }}" \
              --env NODE_ENV=production \
              --env PORT=3000 \
              --max-memory-restart 200M

            # Save PM2 configuration
            pm2 save

            # Clean up
            pnpm store prune
